[Icon Theme]
Name=Numix-uTouch
Comment=Numix icon theme taking design ques from the original Ubuntu Touch

Inherits=Numix

Example=directory-x-normal

# Directory list
Directories=16x16/apps,22x22/apps,24x24/apps,48x48/apps

[16x16/apps]
Size=16
Context=apps
Type=Fixed

[22x22/apps]
Size=22
Context=apps
Type=Fixed

[24x24/apps]
Size=24
Context=apps
Type=Fixed

[48x48/apps]
Size=48
Context=apps
Type=Fixed

[scalable/apps]
Size=16
Context=Applications
MinSize=8
MaxSize=512
Type=Scalable
