[Icon Theme]
Name=Numix-Shine
Comment=Numix icon theme with a glossy design

Inherits=Numix

Example=directory-x-normal

# Directory list
Directories=16x16/applications,22x22/applications,24x24/applications,48x48/applications

[16x16/applications]
Size=16
Context=Applications
Type=Fixed

[22x22/applications]
Size=22
Context=Applications
Type=Fixed

[24x24/applications]
Size=24
Context=Applications
Type=Fixed

[48x48/applications]
Size=48
Context=Applications
Type=Fixed