[Icon Theme]
Name=Numix-Shine
Comment=Numix icon theme with a glossy design

Inherits=Numix

Example=directory-x-normal

# Directory list
Directories=48/applications,24/applications,22/applications,16/applications

[16/applications]
Size=16
Context=Applications
Type=Fixed

[22/applications]
Size=22
Context=Applications
Type=Fixed

[24/applications]
Size=24
Context=Applications
Type=Fixed

[48/applications]
Size=48
Context=Applications
Type=Fixed
