[Icon Theme]
Name=Numix-Square
Comment=Numix icon theme with a square apps icons design

Inherits=Numix

Example=directory-x-normal

# Directory list
Directories=16x16/apps,22x22/apps,22x22/status,24x24/apps,48x48/apps

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[22x22/apps]
Size=22
Context=Applications
Type=Fixed

[22x22/status]
Size=22
Context=Status
Type=Fixed

[24x24/apps]
Size=24
Context=Applications
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed
